// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramSellerBot.Persistense.Data;

#nullable disable

namespace TelegramSellerBot.TelegramBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240812235238_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationId")
                        .HasColumnType("integer")
                        .HasColumnName("duration_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("TelegramUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("DurationId")
                        .HasDatabaseName("ix_subscriptions_duration_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_subscriptions_service_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_subscriptions_status_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.SubscriptionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid?>("TelegramBotId")
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_bot_id");

                    b.HasKey("Id")
                        .HasName("pk_subscription_histories");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_histories_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_subscription_histories_status_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_histories_subscription_id");

                    b.HasIndex("TelegramBotId")
                        .HasDatabaseName("ix_subscription_histories_telegram_bot_id");

                    b.ToTable("subscription_histories", (string)null);
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.SubscriptionStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subscription_statuses");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_statuses_id");

                    b.ToTable("subscription_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "inactive"
                        },
                        new
                        {
                            Id = 1,
                            Name = "active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "stoppedbyend"
                        });
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.TelegramBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TelegramBotLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telegram_bot_link");

                    b.HasKey("Id")
                        .HasName("pk_telegram_bots");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_bots_id");

                    b.ToTable("telegram_bots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d6154e8-f1e5-435a-93e2-244a0e27d0ad"),
                            Description = "some description, none more",
                            Name = "Some service #1",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("035b033a-a042-4f10-af8d-faea50fbfcf3"),
                            Description = "some description, none more",
                            Name = "Some service #2",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("64c6f5e9-d535-4eca-a786-ec769b5b70b3"),
                            Description = "some description, none more",
                            Name = "Some service #3",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("395b8881-01ea-4a54-aab1-6e8029afa1de"),
                            Description = "some description, none more",
                            Name = "Some service #4",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("2423888f-e190-4c6f-8c32-27f5fdf3c174"),
                            Description = "some description, none more",
                            Name = "Some service #5",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("8dfac16d-e70e-4add-afab-b62f82dc9263"),
                            Description = "some description, none more",
                            Name = "Some service #6",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("74297ae7-11bd-4db4-81af-3a25738f16e9"),
                            Description = "some description, none more",
                            Name = "Some service #7",
                            TelegramBotLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("afd6aa9a-9582-4af3-beb6-f04725809d46"),
                            Description = "some description, none more",
                            Name = "Some service #8",
                            TelegramBotLink = "https://google.com"
                        });
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.TelegramBotDuration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_telegram_bot_durations");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_bot_durations_id");

                    b.ToTable("telegram_bot_durations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 168,
                            Name = "week"
                        },
                        new
                        {
                            Id = 336,
                            Name = "twoweek"
                        },
                        new
                        {
                            Id = 744,
                            Name = "month"
                        },
                        new
                        {
                            Id = 2232,
                            Name = "threemonth"
                        },
                        new
                        {
                            Id = 4464,
                            Name = "halfyear"
                        },
                        new
                        {
                            Id = 8760,
                            Name = "year"
                        });
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.TelegramBotDurationAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<int>("DurationId")
                        .HasColumnType("integer")
                        .HasColumnName("duration_id");

                    b.Property<Guid>("TelegramBotId")
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_bot_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_bot_duration_availabilities");

                    b.HasIndex("DurationId")
                        .HasDatabaseName("ix_telegram_bot_duration_availabilities_duration_id");

                    b.HasIndex("TelegramBotId")
                        .HasDatabaseName("ix_telegram_bot_duration_availabilities_telegram_bot_id");

                    b.ToTable("telegram_bot_duration_availabilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("1d6154e8-f1e5-435a-93e2-244a0e27d0ad")
                        },
                        new
                        {
                            Id = 2,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("1d6154e8-f1e5-435a-93e2-244a0e27d0ad")
                        },
                        new
                        {
                            Id = 3,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("1d6154e8-f1e5-435a-93e2-244a0e27d0ad")
                        },
                        new
                        {
                            Id = 4,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("035b033a-a042-4f10-af8d-faea50fbfcf3")
                        },
                        new
                        {
                            Id = 5,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("035b033a-a042-4f10-af8d-faea50fbfcf3")
                        },
                        new
                        {
                            Id = 6,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("035b033a-a042-4f10-af8d-faea50fbfcf3")
                        },
                        new
                        {
                            Id = 7,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("64c6f5e9-d535-4eca-a786-ec769b5b70b3")
                        },
                        new
                        {
                            Id = 8,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("64c6f5e9-d535-4eca-a786-ec769b5b70b3")
                        },
                        new
                        {
                            Id = 9,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("64c6f5e9-d535-4eca-a786-ec769b5b70b3")
                        },
                        new
                        {
                            Id = 10,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("395b8881-01ea-4a54-aab1-6e8029afa1de")
                        },
                        new
                        {
                            Id = 11,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("395b8881-01ea-4a54-aab1-6e8029afa1de")
                        },
                        new
                        {
                            Id = 12,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("395b8881-01ea-4a54-aab1-6e8029afa1de")
                        },
                        new
                        {
                            Id = 13,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("2423888f-e190-4c6f-8c32-27f5fdf3c174")
                        },
                        new
                        {
                            Id = 14,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("2423888f-e190-4c6f-8c32-27f5fdf3c174")
                        },
                        new
                        {
                            Id = 15,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("2423888f-e190-4c6f-8c32-27f5fdf3c174")
                        },
                        new
                        {
                            Id = 16,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("8dfac16d-e70e-4add-afab-b62f82dc9263")
                        },
                        new
                        {
                            Id = 17,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("8dfac16d-e70e-4add-afab-b62f82dc9263")
                        },
                        new
                        {
                            Id = 18,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("8dfac16d-e70e-4add-afab-b62f82dc9263")
                        },
                        new
                        {
                            Id = 19,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("74297ae7-11bd-4db4-81af-3a25738f16e9")
                        },
                        new
                        {
                            Id = 20,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("74297ae7-11bd-4db4-81af-3a25738f16e9")
                        },
                        new
                        {
                            Id = 21,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("74297ae7-11bd-4db4-81af-3a25738f16e9")
                        },
                        new
                        {
                            Id = 22,
                            Cost = 100m,
                            DurationId = 168,
                            TelegramBotId = new Guid("afd6aa9a-9582-4af3-beb6-f04725809d46")
                        },
                        new
                        {
                            Id = 23,
                            Cost = 200m,
                            DurationId = 4464,
                            TelegramBotId = new Guid("afd6aa9a-9582-4af3-beb6-f04725809d46")
                        },
                        new
                        {
                            Id = 24,
                            Cost = 3100m,
                            DurationId = 8760,
                            TelegramBotId = new Guid("afd6aa9a-9582-4af3-beb6-f04725809d46")
                        });
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.Subscription", b =>
                {
                    b.HasOne("TelegramSellerBot.Core.Entities.TelegramBotDuration", "Duration")
                        .WithMany()
                        .HasForeignKey("DurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_telegram_bot_durations_duration_id");

                    b.HasOne("TelegramSellerBot.Core.Entities.TelegramBot", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_subscriptions_telegram_bots_service_id");

                    b.HasOne("TelegramSellerBot.Core.Entities.SubscriptionStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_subscription_statuses_status_id");

                    b.Navigation("Duration");

                    b.Navigation("Service");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.SubscriptionHistory", b =>
                {
                    b.HasOne("TelegramSellerBot.Core.Entities.SubscriptionStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_histories_subscription_statuses_status_id");

                    b.HasOne("TelegramSellerBot.Core.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_subscription_histories_subscriptions_subscription_id");

                    b.HasOne("TelegramSellerBot.Core.Entities.TelegramBot", "TelegramBot")
                        .WithMany()
                        .HasForeignKey("TelegramBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_subscription_histories_telegram_bots_telegram_bot_id");

                    b.Navigation("Status");

                    b.Navigation("Subscription");

                    b.Navigation("TelegramBot");
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.TelegramBotDurationAvailability", b =>
                {
                    b.HasOne("TelegramSellerBot.Core.Entities.TelegramBotDuration", "Duration")
                        .WithMany()
                        .HasForeignKey("DurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_bot_duration_availabilities_telegram_bot_durations");

                    b.HasOne("TelegramSellerBot.Core.Entities.TelegramBot", "TelegramBot")
                        .WithMany("Availabilities")
                        .HasForeignKey("TelegramBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_bot_duration_availabilities_telegram_bots_telegram");

                    b.Navigation("Duration");

                    b.Navigation("TelegramBot");
                });

            modelBuilder.Entity("TelegramSellerBot.Core.Entities.TelegramBot", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
